# Build numbering format
name: $(BuildID)

trigger:
  branches:
    include:
      - cicd-resource-deployment
  paths:
    include:
      - 'nba-front-end/*'
pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'